#pragma once
#define CALCM_COMMAND_ENTERED			100
#define CALCM_CHARACTER_ENTERED			101
#define CALCM_ENTER_PRESSED				102
#define CALCM_SHIFT_PRESSED				103
#define CALCM_PROCEDURE_PRESSED			104
#define CALCM_PLUS_MINUS_PRESSED		105
#define CALCM_MODEL_CHANGED				106
